//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductSurvey.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Survey
    {
        public int SurveyId { get; set; }
        public string SurveyName { get; set; }
        public string Title { get; set; }
    }
}
