//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductSurvey.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAnswer
    {
        public int UserSurveyId { get; set; }
        public string UserId { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public Nullable<int> SelectedRate { get; set; }
        public string UserEmail { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> SurveyId { get; set; }
    }
}
